// <auto-generated />
using System;
using GameLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameLibrary.Migrations
{
    [DbContext(typeof(LibDbContext))]
    partial class LibDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameLibrary.Models.Game", b =>
                {
                    b.Property<long?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("GameId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

					b.Property<string>("GenreId")
						.HasColumnType("bigint");

					b.Property<string>("DeveloperId")
						.HasColumnType("bigint");

					b.HasKey("GameId");

					b.HasIndex("GenreId");

					b.HasIndex("DeveloperId");

                    b.ToTable("Game");
                });

			modelBuilder.Entity("GameLibrary.Models.Developer", b =>
			{
				b.Property<long?>("DeveloperId")
					.ValueGeneratedOnAdd()
					.HasColumnType("bigint");

				SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("DeveloperId"), 1L, 1);

				b.Property<string>("Name")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.HasKey("DeveloperId");

				b.ToTable("Developer");
			});

			modelBuilder.Entity("GameLibrary.Models.Genre", b =>
			{
				b.Property<long?>("GenreId")
					.ValueGeneratedOnAdd()
					.HasColumnType("bigint");

				SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenreId"), 1L, 1);

				b.Property<string>("Name")
					.IsRequired()
					.HasColumnType("nvarchar(max)");

				b.HasKey("GenreId");

				b.ToTable("Genre");
			});

			modelBuilder.Entity("WebApp.Models.Game", b =>
			{
				b.HasOne("WebApp.Models.Genre", "Genre")
					.WithMany("Game")
					.HasForeignKey("GenreId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.HasOne("WebApp.Models.Developer", "Developer")
					.WithMany("Game")
					.HasForeignKey("DeveloperId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.Navigation("Genre");

				b.Navigation("Developer");
			});

			modelBuilder.Entity("WebApp.Models.Genre", b =>
			{
				b.Navigation("Game");
			});

			modelBuilder.Entity("WebApp.Models.Dveloper", b =>
			{
				b.Navigation("Game");
			});

#pragma warning restore 612, 618
		}
    }
}
